/* eslint-disable */
// Generated by `pnpm cf-typegen` — run after wrangler.toml / .env.schema changes.
interface CloudflareBindings {
  DB: D1Database;
  ENVIRONMENT: string;
  SERVICE_NAME: string;
  BETTER_AUTH_URL: string;
  BETTER_AUTH_SECRET: string;
  CORS_ORIGINS?: string;
  TRUSTED_ORIGINS?: string;
  RATE_LIMIT_TTL?: string;
  RATE_LIMIT_MAX?: string;
  AUTH_RATE_LIMIT_TTL?: string;
  AUTH_RATE_LIMIT_MAX?: string;
  EMAIL_PROVIDER?: string;
  EMAIL_FROM?: string;
  RESEND_API_KEY?: string;
  __VARLOCK_ENV?: string;
  __VARLOCK_ENV_CHUNKS?: string;
}
