/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=<generated-env> --include-runtime=false --env-interface=CloudflareBindings` (hash: fe99a5b3177ee3a793141d284b298722)
interface __BaseEnv_CloudflareBindings {
  DB: D1Database;
  EMAIL: SendEmail;
  BILLING_QUEUE: Queue;
  ENVIRONMENT: string;
  SERVICE_NAME: string;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
  APP_URL: string;
  CORS_ORIGINS: string;
  TRUSTED_ORIGINS: string;
  RATE_LIMIT_TTL: string;
  RATE_LIMIT_MAX: string;
  AUTH_RATE_LIMIT_TTL: string;
  AUTH_RATE_LIMIT_MAX: string;
  WEBHOOK_RATE_LIMIT_TTL: string;
  WEBHOOK_RATE_LIMIT_MAX: string;
  EMAIL_PROVIDER: string;
  EMAIL_FROM: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  REVENUECAT_WEBHOOK_AUTHORIZATION: string;
  REVENUECAT_SECRET_API_KEY: string;
  BILLING_ENTITLEMENT_KEY: string;
  BILLING_GRACE_PERIOD_DAYS: string;
  BILLING_EVENT_RETENTION_DAYS: string;
  BILLING_RECONCILIATION_LIMIT: string;
  STRIPE_PRICE_MONTHLY: string;
  STRIPE_PRICE_YEARLY: string;
  REVENUECAT_ENTITLEMENT_ID: string;
  REVENUECAT_OFFERING_ID: string;
  REVENUECAT_IOS_APP_ID: string;
  REVENUECAT_ANDROID_APP_ID: string;
  REVENUECAT_IOS_PRODUCT_MONTHLY: string;
  REVENUECAT_IOS_PRODUCT_YEARLY: string;
  REVENUECAT_ANDROID_PRODUCT_MONTHLY: string;
  REVENUECAT_ANDROID_PRODUCT_YEARLY: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "ENVIRONMENT"
      | "SERVICE_NAME"
      | "BETTER_AUTH_SECRET"
      | "BETTER_AUTH_URL"
      | "APP_URL"
      | "CORS_ORIGINS"
      | "TRUSTED_ORIGINS"
      | "RATE_LIMIT_TTL"
      | "RATE_LIMIT_MAX"
      | "AUTH_RATE_LIMIT_TTL"
      | "AUTH_RATE_LIMIT_MAX"
      | "WEBHOOK_RATE_LIMIT_TTL"
      | "WEBHOOK_RATE_LIMIT_MAX"
      | "EMAIL_PROVIDER"
      | "EMAIL_FROM"
      | "STRIPE_SECRET_KEY"
      | "STRIPE_WEBHOOK_SECRET"
      | "REVENUECAT_WEBHOOK_AUTHORIZATION"
      | "REVENUECAT_SECRET_API_KEY"
      | "BILLING_ENTITLEMENT_KEY"
      | "BILLING_GRACE_PERIOD_DAYS"
      | "BILLING_EVENT_RETENTION_DAYS"
      | "BILLING_RECONCILIATION_LIMIT"
      | "STRIPE_PRICE_MONTHLY"
      | "STRIPE_PRICE_YEARLY"
      | "REVENUECAT_ENTITLEMENT_ID"
      | "REVENUECAT_OFFERING_ID"
      | "REVENUECAT_IOS_APP_ID"
      | "REVENUECAT_ANDROID_APP_ID"
      | "REVENUECAT_IOS_PRODUCT_MONTHLY"
      | "REVENUECAT_IOS_PRODUCT_YEARLY"
      | "REVENUECAT_ANDROID_PRODUCT_MONTHLY"
      | "REVENUECAT_ANDROID_PRODUCT_YEARLY"
    >
  > {}
}
