/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/tmp/varlock-types-env-febc11122ee0681a --include-runtime=false --env-interface=CloudflareBindings` (hash: 60675f878decf2476994d1b5aaecbd84)
interface __BaseEnv_CloudflareBindings {
  DB: D1Database;
  EMAIL: SendEmail;
  ENVIRONMENT: string;
  SERVICE_NAME: string;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
  APP_URL: string;
  CORS_ORIGINS: string;
  TRUSTED_ORIGINS: string;
  RATE_LIMIT_TTL: string;
  RATE_LIMIT_MAX: string;
  AUTH_RATE_LIMIT_TTL: string;
  AUTH_RATE_LIMIT_MAX: string;
  EMAIL_PROVIDER: string;
  EMAIL_FROM: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  REVENUECAT_WEBHOOK_AUTHORIZATION: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "ENVIRONMENT"
      | "SERVICE_NAME"
      | "BETTER_AUTH_SECRET"
      | "BETTER_AUTH_URL"
      | "APP_URL"
      | "CORS_ORIGINS"
      | "TRUSTED_ORIGINS"
      | "RATE_LIMIT_TTL"
      | "RATE_LIMIT_MAX"
      | "AUTH_RATE_LIMIT_TTL"
      | "AUTH_RATE_LIMIT_MAX"
      | "EMAIL_PROVIDER"
      | "EMAIL_FROM"
      | "STRIPE_SECRET_KEY"
      | "STRIPE_WEBHOOK_SECRET"
      | "REVENUECAT_WEBHOOK_AUTHORIZATION"
    >
  > {}
}
